### ISSUE TITLE
Firmware Sources

### ISSUE THREAD

**Issue by scipione205** [bq/witbox#3]
Hi,
I'm using a Witbox and I'm encountering some annoying things with the firmware. Please upload the sources, so we users could participate with the company in improving the printer's performance.

**Comment by Obijuan** [comment]
Hi scipione!

You can find the source for the witbox and hephestos firmware in this fork

https://github.com/bq/Marlin

Best regards

**Comment by scipione205** [comment]
Thank you Obi Juan! May the force be with you.
